# Generated by Django 6.1.1 on 2026-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobMelaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('documents', 'Required Documents'), ('eligibility', 'Eligibility Criteria'), ('instructions', 'Reporting & Guidelines'), ('dress_code', 'Dress Code'), ('general', 'General Rules')], default='documents', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Mela Requirement',
                'verbose_name_plural': 'Job Mela Requirements',
                'ordering': ['order', 'id'],
            },
        ),
    ]
